### ISSUE TITLE
Falha no build

### ISSUE THREAD

**Issue by ciceroduarte** [pabloborsone/PokemonStudy-MVVM-C#1]
Baixei o projeto e não esta compilando, vi que o problema esta nas fontes. No `Build Phases` não esta apontando para a Font do projeto, e sim para:

```../../../../../Library/Fonts```

Seria legal você adicionar um CI no projeto, recomendo o [Bitrise](https://www.bitrise.io) ou [Travis](https://travis-ci.org). Assim você garante que seus commits estão funcionando em qualquer ambiente 🚀

**Comment by pabloborsone** [comment]
Fixed.
